hook.Add( "PlayerInitialSpawn", "PrecacheKatana", function( ply )
	ply:SendLua( "util.PrecacheModel( \"models/weapons/w_katana.mdl\" )" )
	ply:SendLua( "util.PrecacheModel( \"models/weapons/v_katana.mdl\" )" )
	ply:SendLua( "util.PrecacheSound( \"sound/katana/glass_hit_1.wav\" )" )
	ply:SendLua( "util.PrecacheSound( \"sound/katana/wood_hit_1.wav\" )" )
	ply:SendLua( "util.PrecacheSound( \"sound/katana/ground_hit_1.wav\" )" )
	ply:SendLua( "util.PrecacheSound( \"sound/katana/metal_hit_1.wav\" )" )
	ply:SendLua( "util.PrecacheSound( \"sound/katana/draw.wav\" )" )
end )